# Copyright lowRISC Contributors.
# SPDX-License-Identifier: Apache-2.0

[book]
language = "en"
multilingual = false
src = "."
title = "Sonata Software"

[output.html]
git-repository-url = "https://github.com/lowRISC/sonata-software"
edit-url-template = "https://github.com/lowRISC/sonata-software/edit/main/{path}"

[preprocessor.replace]
after = ["links"]

# Replace all links to a README.md to with a link to an index.md
link_replacements = [
    {regex = '^(?P<path>[^:#\?]*)README\.md(?P<suffix>[?#].*)?', replacement = '${path}index.md${suffix}'},
]

[[preprocessor.replace.local_link_replacements]]
# Replace all paths pointing to something in cheriot-rtos
# to a link pointing to it in github.
regex = '^cheriot-rtos/(?P<path>.*)?'
replacement = 'https://github.com/CHERIoT-Platform/cheriot-rtos/tree/main/${path}'

[[preprocessor.replace.local_link_replacements]]
# Replace all paths pointing to something in this repository,
# that ends with .cc, .hh, .h, .rego, .lua or / (for directories)
# to a link pointing to to in github.
regex = '.*(\/|\.(cc|hh|h|rego|lua))$'
replacement = 'https://github.com/lowRISC/sonata-software/tree/main/${0}'
